### PR TITLE
Make debugging playbot easier

### LINKED ISSUE #225: Playbot crashes difficult to debug
Right now if any thread in playbot crashes (e.g. panics) then the rest of the connections keep going and the logs have to be hunted through to find the culprit. Perhaps some tweaks could be done to assist this?

* For all programs run, debug the name of the channel as well
* Kill the entire process whenever a thread panics

Thoughts @jonas-schievink?

### PR DESCRIPTION
**Pull request by jonas-schievink**
Sets names for threads, kills the whole process when a thread panics, and logs the channel from which playbot was talked to.

Closes #225

### CODE REVIEW

File: src/bin/playbot.rs [hunk 1]
```diff
@@ -250,9 +253,17 @@ fn main() {
                 shorten_key: bitly_key.clone(),
                 cache: cache.clone(),
             };
-            threads.push(thread::spawn(move || {
-                bot.main_loop();
-            }));
+            threads.push(thread::Builder::new()
+                                         .name(format!("{}@{}", nick, server_addr))
+                                         .spawn(move || {
+                if let Err(e) = catch_unwind(AssertUnwindSafe(|| bot.main_loop())) {
```
Comment (alexcrichton) [inline src/bin/playbot.rs]: If this used `move`, I think it could avoid the `AssertUnwindSafe` usage, right?

File: src/bin/playbot.rs [hunk 2]
```diff
@@ -250,9 +253,17 @@ fn main() {
...
+                    error!("{:?}", e);
```
Comment (alexcrichton) [inline src/bin/playbot.rs]: Unfortunately this may not provide too much information as the `Debug` implementation for `Any` just prints "Any". This error should already have been printed, however, so it may not be necessary to print it again. Perhaps this could just print out a string that's easily greppable?

File: src/bin/playbot.rs (hunk 1 above)
Comment (jonas-schievink) [inline src/bin/playbot.rs]: That makes rustc complain about a *lot* of unsatisfied `RefUnwindSafe` bounds somewhere in the `irc` crate.

File: src/bin/playbot.rs (hunk 2 above)
Comment (jonas-schievink) [inline src/bin/playbot.rs]: Oh wow I didn't realise that Debug impl existed :/

Comment (jonas-schievink) [inline src/bin/playbot.rs]: Okay, made it print something more useful.

**Comment by alexcrichton** [comment]
Ok, thanks!
